oculus changes

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,56 +1,53 @@
 #!/bin/bash
 
-if [ $# -le 0 ]
-  then 
+copy_files() {
+  cp "program$1.h" program.h
+  cp "mainwindow$1.ui" mainwindow.ui
+  cp "adblink$1.ico" adblink.ico
+  cp "adblink$1.icns" adblink.icns
+  cp "assets/menu$1.html" assets/menu.html
+  cp "assets/adblink$1.png" assets/adblink.png
+  
+  if [ $1 -ne 3 ]; then
+    cp "preferencesdialog$1.ui" preferencesdialog.ui
+  fi
+}
+
+if [ $# -le 0 ]; then 
    echo "set up adblink 1 2 3"
-  exit 1
- fi
-
-
-
-if [ $1 -eq 1 ];
- then
-  cp program1.h program.h
-  cp mainwindow1.ui mainwindow.ui
-  cp preferencesdialog1.ui preferencesdialog.ui
-  cp adblink1.pro adblink.pro
-  cp adblink1.ico adblink.ico
-  cp adblink1.icns adblink.icns
-  cp assets/menu1.html assets/menu.html
-  cp assets/adblink1.png assets/adblink.png
-  echo "adblink1 will compile"
-  exit 0
+   exit 1
 fi
 
+pro_file="./adblink.pro"
+target_name=""
 
-if [ $1 -eq 2 ];
- then
-  cp program2.h program.h
-  cp mainwindow2.ui mainwindow.ui
-  cp preferencesdialog2.ui preferencesdialog.ui
-  cp adblink2.pro adblink.pro
-  cp adblink2.ico adblink.ico
-  cp adblink2.icns adblink.icns
-  cp assets/menu2.html assets/menu.html
-  cp assets/adblink2.png assets/adblink.png
-  echo "adblink2 will compile"
-  exit 0
+case $1 in
+  1)
+    copy_files 1
+    target_name="adblink"
+    ;;
+  2)
+    copy_files 2
+    target_name="adblink2"
+    ;;
+  3)
+    copy_files 3
+    target_name="wsalink"
+    ;;
+  *)
+    echo "Invalid build number"
+    exit 1
+    ;;
+esac
+
+if [[ "$(uname)" == "Darwin" ]]; then
+    # macOS
+    sed_command="sed -i ''"
+else
+    # Linux
+    sed_command="sed -i''"
 fi
 
-if [ $1 -eq 3 ];
- then
-  cp program3.h program.h
-  cp mainwindow3.ui mainwindow.ui
-  cp adblink3.pro adblink.pro
-  cp adblink3.ico adblink.ico
-  cp adblink3.icns adblink.icns  
-  cp assets/menu3.html assets/menu.html
-  cp assets/adblink3.png assets/adblink.png
-  echo "adblink 3 will compile"
-  exit 0
-fi
-
- echo "set up adblink 1 2 3"
-
+eval "$sed_command 's/TARGET = .*/TARGET = $target_name/' $pro_file" 2>/dev/null
+echo "$target_name will compile"
 exit 0
-
